version: "3.5"

services:

  elasticsearch:
    image:  elasticsearch:6.6.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  web:
    image:  nginx:alpine
    container_name: elastic-symfony-demo-web
    volumes:  
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
     - php-fpm
  
  php-fpm:
    build: docker/php
    working_dir: /app
    volumes:
      - ./app:/app

